<a href="https://colab.research.google.com/github/LakshmiP1/Generative-AI/blob/main/word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px


from wordcloud import WordCloud
import nltk
import re
import string
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer


stop_words = stopwords.words()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [57]:
data = pd.read_csv("sample.csv")

In [58]:
data.head()

tweet_id     author_id  inbound                      created_at  \
0    119237        105834     True  Wed Oct 11 06:55:44 +0000 2017   
1    119238  ChaseSupport    False  Wed Oct 11 13:25:49 +0000 2017   
2    119239        105835     True  Wed Oct 11 13:00:09 +0000 2017   
3    119240  VirginTrains    False  Tue Oct 10 15:16:08 +0000 2017   
4    119241        105836     True  Tue Oct 10 15:17:21 +0000 2017   

                                                text response_tweet_id  \
0  @AppleSupport causing the reply to be disregar...            119236   
1  @105835 Your business means a lot to us. Pleas...               NaN   
2  @76328 I really hope you all change but I'm su...            119238   
3  @105836 LiveChat is online at the moment - htt...            119241   
4  @VirginTrains see attached error message. I've...            119243   

   in_response_to_tweet_id  
0                      NaN  
1                 119239.0  
2                      NaN  
3                 119242.0  
4                 119240.0

In [59]:
def cleaning(text):
    # converting to lowercase, removing URL links, special characters, punctuations...
    text = text.lower() # converting to lowercase
    text = re.sub('https?://\S+|www\.\S+', '', text) # removing URL links
    text = re.sub(r"\b\d+\b", "", text) # removing number
    text = re.sub('<.*?>+', '', text) # removing special characters,
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text) # punctuations
    text = re.sub('\n', '', text)
    text = re.sub('[’“”…]', '', text)

    #removing emoji:
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    text = emoji_pattern.sub(r'', text)

   # removing short form:

    text=re.sub("isn't",'is not',text)
    text=re.sub("he's",'he is',text)
    text=re.sub("wasn't",'was not',text)
    text=re.sub("there's",'there is',text)
    text=re.sub("couldn't",'could not',text)
    text=re.sub("won't",'will not',text)
    text=re.sub("they're",'they are',text)
    text=re.sub("she's",'she is',text)
    text=re.sub("There's",'there is',text)
    text=re.sub("wouldn't",'would not',text)
    text=re.sub("haven't",'have not',text)
    text=re.sub("That's",'That is',text)
    text=re.sub("you've",'you have',text)
    text=re.sub("He's",'He is',text)
    text=re.sub("what's",'what is',text)
    text=re.sub("weren't",'were not',text)
    text=re.sub("we're",'we are',text)
    text=re.sub("hasn't",'has not',text)
    text=re.sub("you'd",'you would',text)
    text=re.sub("shouldn't",'should not',text)
    text=re.sub("let's",'let us',text)
    text=re.sub("they've",'they have',text)
    text=re.sub("You'll",'You will',text)
    text=re.sub("i'm",'i am',text)
    text=re.sub("we've",'we have',text)
    text=re.sub("it's",'it is',text)
    text=re.sub("don't",'do not',text)
    text=re.sub("that´s",'that is',text)
    text=re.sub("I´m",'I am',text)
    text=re.sub("it’s",'it is',text)
    text=re.sub("she´s",'she is',text)
    text=re.sub("he’s'",'he is',text)
    text=re.sub('I’m','I am',text)
    text=re.sub('I’d','I did',text)
    text=re.sub("he’s'",'he is',text)
    text=re.sub('there’s','there is',text)


    return text

dt = data['text'].apply(cleaning)

In [60]:
dt

0     applesupport causing the reply to be disregard...
1      your business means a lot to us please dm you...
2      i really hope you all change but im sure you ...
3      livechat is online at the moment   or contact...
4     virgintrains see attached error message ive tr...
                            ...                        
88     i wish amazon had an option of where i can ju...
89                they reschedule my shit for tomorrow 
90     hey sara sorry to hear of the issues you are ...
91    tesco bit of both  finding the layout cumberso...
92     if that doesnt help please dm your full name ...
Name: text, Length: 93, dtype: object

In [61]:
# remove stop word:
data['no_sw'] = dt.apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [62]:
data['no_sw']

0     applesupport causing reply disregarded tapped ...
1     business means lot dm zip code additional deta...
2                                           hope change
3     livechat online moment contact option leave me...
4     virgintrains attached error message ive leavin...
                            ...                        
88    wish amazon option shipped ups store avoid lot...
89                             reschedule shit tomorrow
90    hey sorry hear issues lay speed website respon...
91    tesco bit finding layout cumbersome removing i...
92    dm full address email including browser device...
Name: no_sw, Length: 93, dtype: object

In [63]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-dat

True

In [64]:
from nltk.stem import WordNetLemmatizer

lematizer=WordNetLemmatizer()

def lemmatizer_words(text):
    return " ".join([lematizer.lemmatize(word,"v") for word in text.split()])

data['lemma_text']=data['no_sw'].apply(lambda text: lemmatizer_words(text))
data['lemma_text'].head()

0    applesupport cause reply disregard tap notific...
1    business mean lot dm zip code additional detai...
2                                          hope change
3    livechat online moment contact option leave me...
4    virgintrains attach error message ive leave vo...
Name: lemma_text, dtype: object

In [65]:
def word_toke(text):
  words = re.findall(r'\b\w+\b', text)
  return ",".join(words)

In [66]:
data['tok_text']=data['lemma_text'].apply(lambda text: word_toke(text))
data['tok_text'].head()

0    applesupport,cause,reply,disregard,tap,notific...
1    business,mean,lot,dm,zip,code,additional,detai...
2                                          hope,change
3    livechat,online,moment,contact,option,leave,me...
4    virgintrains,attach,error,message,ive,leave,vo...
Name: tok_text, dtype: object

1.Count or frequency based method:

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [68]:
tfidf=TfidfVectorizer()

In [69]:
tfidf.fit_transform(data["tok_text"]).toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.34030422],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [70]:
word_set = tfidf.get_feature_names_out()

In [71]:
tfidf.idf_

array([4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 , 4.44468249,
       4.15700042, 4.8501476 , 4.15700042, 4.8501476 , 4.8501476 ,
       4.8501476 , 4.15700042, 4.8501476 , 4.8501476 , 4.8501476 ,
       4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 , 3.75153531,
       4.44468249, 4.8501476 , 4.44468249, 3.93385687, 3.93385687,
       3.05838813, 4.8501476 , 3.75153531, 4.8501476 , 4.8501476 ,
       4.8501476 , 4.8501476 , 4.44468249, 4.8501476 , 4.8501476 ,
       4.8501476 , 4.8501476 , 3.59738463, 4.8501476 , 3.93385687,
       4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 ,
       4.8501476 , 4.44468249, 4.44468249, 4.8501476 , 4.44468249,
       4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 ,
       4.44468249, 4.8501476 , 4.8501476 , 4.44468249, 4.8501476 ,
       3.59738463, 4.8501476 , 4.8501476 , 4.44468249, 4.8501476 ,
       4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 ,
       4.8501476 , 4.8501476 , 4.8501476 , 4.8501476 , 4.85014

#### BOW

In [72]:
data["tok_text"] = data["tok_text"].apply(lambda x: " ".join([word for word in x if word not in stopwords.words("english")]))

In [73]:
from sklearn.feature_extraction.text import CountVectorizer

In [74]:
BOW=CountVectorizer()

In [75]:
import numpy as np


In [76]:
text_array = np.array(data["tok_text"])

In [77]:
document_matrix = BOW.fit_transform(data["text"])

In [78]:
document_matrix

<93x677 sparse matrix of type '<class 'numpy.int64'>'
	with 1763 stored elements in Compressed Sparse Row format>

In [79]:
BOW.vocabulary_

{'applesupport': 103,
 'causing': 161,
 'the': 594,
 'reply': 495,
 'to': 608,
 'be': 123,
 'disregarded': 215,
 'and': 94,
 'tapped': 582,
 'notification': 420,
 'under': 622,
 'keyboard': 347,
 'is': 332,
 'opened': 437,
 '105835': 6,
 'your': 674,
 'business': 145,
 'means': 389,
 'lot': 379,
 'us': 632,
 'please': 461,
 'dm': 217,
 'name': 412,
 'zip': 675,
 'code': 174,
 'additional': 70,
 'details': 207,
 'about': 66,
 'concern': 181,
 'rr': 502,
 'https': 314,
 'co': 172,
 'znuu1vjn9r': 676,
 '76328': 54,
 'really': 483,
 'hope': 305,
 'you': 673,
 'all': 84,
 'change': 163,
 'but': 146,
 'sure': 571,
 'won': 665,
 'because': 125,
 'don': 221,
 'have': 290,
 '105836': 7,
 'livechat': 369,
 'online': 435,
 'at': 114,
 'moment': 403,
 'sy94vtu8kq': 574,
 'or': 441,
 'contact': 184,
 '03331': 1,
 '031': 0,
 'option': 440,
 'leave': 359,
 'message': 390,
 'request': 496,
 'call': 152,
 'back': 120,
 'virgintrains': 640,
 'see': 511,
 'attached': 115,
 'error': 233,
 've': 636,
 'tri

In [80]:
document_matrix[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

## Word2vec ---- CBOW

In [81]:
from gensim.models import Word2Vec

In [82]:
sentences = data['tok_text']

In [83]:
# Train the CBOW model
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4, sg=0)

In [84]:
# Access word vectors
word_vectors = model.wv

In [85]:
word_vectors

In [86]:
vectors=model.wv.get_normed_vectors()

In [87]:
vectors

array([[-0.09550857,  0.11548644,  0.04777924, ..., -0.13627264,
         0.00530112,  0.11336929],
       [-0.10056394,  0.11826065,  0.04833058, ..., -0.13327448,
         0.0004248 ,  0.11253638],
       [-0.09624721,  0.11800814,  0.04277185, ..., -0.13294688,
         0.00864673,  0.10737744],
       ...,
       [-0.10957316,  0.11155381,  0.03012509, ..., -0.12677921,
         0.01626691,  0.11521658],
       [-0.07530414,  0.14216429,  0.03004978, ..., -0.0952079 ,
        -0.04440735,  0.07679743],
       [-0.0685431 ,  0.11343023,  0.01601479, ..., -0.1613814 ,
         0.02864661,  0.13354701]], dtype=float32)

In [88]:
model.wv.get_normed_vectors().shape

(29, 100)

In [89]:
y=model.wv.index_to_key

In [90]:
y

[' ',
 ',',
 'e',
 'r',
 'p',
 'l',
 'n',
 'c',
 'u',
 'h',
 'g',
 'v',
 'f',
 'k',
 'b',
 'w',
 'x',
 'j',
 '1',
 '2',
 '0',
 '3',
 'z',
 '7',
 'q',
 '8',
 '6',
 '4',
 '5']

### Word2Vec -- skipgram


In [91]:
from gensim.models import Word2Vec


In [92]:
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4, sg=1)

In [93]:
# Access word vectors
word_vectors = model.wv

In [94]:
vectors=model.wv.get_normed_vectors()

## If we have no label data, then we have to do

1.Collect or Generate Labels: If you have a dataset where you've generated the CBOW embeddings, you likely had some original text data with labels. You could use these labels to train a classifier.

Unsupervised or Semi-Supervised Learning: If labeled data is not available, you might explore unsupervised or semi-supervised learning techniques that don't require labeled data. Techniques like clustering or self-training might be applicable depending on your specific problem.

Embedding-based Similarity: You can also use the CBOW embeddings for tasks like similarity measurement, where you compare similarity between two pieces of text based on their vector representations. This doesn't require labeled data.

Transfer Learning: If you have access to pre-trained word embeddings like Word2Vec, GloVe, or FastText, you might leverage these embeddings in transfer learning scenarios where you fine-tune a model on a downstream task using these embeddings.